"""Rebuild TextAtlas5M PPT2Details + PPT2Structured JSON shards.

Images already exist on disk (generated by process_data.py with uid=md5(img_bytes[:1024])).
This script downloads parquet data from HuggingFace, computes matching UIDs,
and creates JSON records for existing images.

Usage (run on cpu_light):
    python3 scripts/rebuild_textatlas_json.py
"""

import hashlib
import json
import os

from datasets import Image as HFImage
from datasets import load_dataset

OUTPUT_BASE = "/mnt/bn/search-auto-eval-v2/zhouwei/LightMGT/data/textatlas5m"
SHARD_SIZE = 10000

# These subsets were processed by process_data.py (uid = md5 of first 1KB of raw bytes, ext=png)
SUBSETS = ["PPT2Details", "PPT2Structured"]


def main():
    for subset_name in SUBSETS:
        print(f"\n{'='*60}")
        print(f"Rebuilding JSON for {subset_name}...")
        print(f"{'='*60}")

        image_dir = os.path.join(OUTPUT_BASE, f"images/textatlas_{subset_name}")

        # Build set of existing image filenames
        existing = set(os.listdir(image_dir))
        print(f"  {len(existing)} existing images on disk")

        # Load dataset WITHOUT decoding images (get raw bytes)
        print(f"  Loading {subset_name} from HuggingFace (raw bytes mode)...")
        ds = load_dataset("CSU-JPG/TextAtlas5M", subset_name, split="train")
        ds = ds.cast_column("image", HFImage(decode=False))
        print(f"  {len(ds)} rows loaded")

        records = []
        matched = 0
        skipped_no_caption = 0
        skipped_no_match = 0
        skipped_no_bytes = 0

        for i in range(len(ds)):
            if i % 50000 == 0 and i > 0:
                print(f"  Processed {i}/{len(ds)}, matched {matched}, "
                      f"no_match {skipped_no_match}")

            item = ds[i]
            annotation = item.get("annotation", "")
            if not annotation:
                skipped_no_caption += 1
                continue

            img_data = item.get("image", {})
            if isinstance(img_data, dict):
                img_bytes = img_data.get("bytes", b"")
            elif isinstance(img_data, bytes):
                img_bytes = img_data
            else:
                skipped_no_bytes += 1
                continue

            if not img_bytes:
                skipped_no_bytes += 1
                continue

            # Same UID logic as process_data.py: md5 of first 1KB
            uid = hashlib.md5(img_bytes[:1024]).hexdigest()
            fname = f"{uid}.png"

            if fname in existing:
                # Get dimensions from existing file
                from PIL import Image
                img_path = os.path.join(image_dir, fname)
                try:
                    with Image.open(img_path) as img:
                        w, h = img.size
                except Exception:
                    skipped_no_match += 1
                    continue

                records.append({
                    "uid": uid,
                    "caption": annotation,
                    "image": f"images/textatlas_{subset_name}/{fname}",
                    "height": h,
                    "width": w,
                })
                matched += 1
            else:
                skipped_no_match += 1

        print(f"\n  {subset_name} results:")
        print(f"    Matched: {matched}")
        print(f"    No caption: {skipped_no_caption}")
        print(f"    No bytes: {skipped_no_bytes}")
        print(f"    No match on disk: {skipped_no_match}")

        # Write JSON shards
        for j in range(0, len(records), SHARD_SIZE):
            shard = records[j:j + SHARD_SIZE]
            shard_idx = j // SHARD_SIZE
            shard_path = os.path.join(
                OUTPUT_BASE, f"textatlas5m_{subset_name}_{shard_idx:04d}.json"
            )
            with open(shard_path, "w") as f:
                json.dump(shard, f, ensure_ascii=False)

        n_shards = (len(records) + SHARD_SIZE - 1) // SHARD_SIZE if records else 0
        print(f"    Wrote {n_shards} JSON shards ({len(records)} records)")

    print("\nALL DONE")


if __name__ == "__main__":
    main()
